#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: read-pods
#  namespace: test
#subjects:
#- kind: ServiceAccount
#  name: test
#  namespace: test
#roleRef:
#  kind: Role
#  name: pod-reader
#  apiGroup: rbac.authorization.k8s.io

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web
  namespace: default
subjects:
- kind: ServiceAccount
  name: nginx-ingress-controller
  namespace: default
roleRef:
  kind: Role
  name: web
  apiGroup: rbac.authorization.k8s.io
