#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  namespace: test
#  name: pod-reader
#rules:
#- apiGroups: [""] # "" indicates the core API group
#  resources: ["pods"]
#  verbs: ["get"]
  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: web
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
